export default [
  {
    id: 'de8bb1db-caa4-4534-992a-322645763d69',
    logNumber: '10VL02863',
    status: 'pending',
    fiscalYear: '2018/19',
    visitStartDate: '2019-01-01',
    visitEndDate: '2019-03-01',
    visitTime: '1:00 pm',
    onGoing: true,
    contactPrimary: 'primary contact info 1',
    contactSecondary: 'secondary contact info 1',
    campus: 'gold camp',
    room: 'room-1',
    roomOther: null,
    accessArea: 'access-area-1',
    accessAreaOther: 'other-access-area',
    companyName: 'ryans awesome org',
    visitReason: 'reason for visiting...',
    specialInstructions: 'instructions..',
    visitors: [],
  },
  {
    id: '53dbf504-438b-4139-aa39-1958c708aee5',
    logNumber: '99AB02863',
    status: 'draft',
    fiscalYear: '2018/19',
    visitStartDate: '2017-01-02',
    visitEndDate: '2030-03-02',
    visitTime: '1:00 pm',
    onGoing: false,
    contactPrimary: 'primary contact info 2',
    contactSecondary: 'secondary contact info 2',
    campus: 'gold camp',
    room: 'other',
    roomOther: 'other-room',
    accessArea: 'other',
    accessAreaOther: 'other-access-area',
    companyName: 'ryans awesome org',
    visitReason: 'reason for visiting...',
    specialInstructions: 'instructions..',
    visitors: [
      {
        badgeType: 'sticky',
        securedArea: 'custodial',
        visitorName: 'visitor-1',
      },
      {
        badgeType: 'badge',
        securedArea: 'none',
        visitorName: 'visitor-2',
      },
    ],
  },
];
